### ISSUE TITLE
Evaluating error

### ISSUE THREAD

**Issue by decim** [mappum/electron-webrtc#16]
Node - v5.1.0
Linux Ubuntu - v15.04
webtorrent-hybrid - v.1.0.0

I have tested webtorrent-hybrid with 8 torrent hashes at the same time and after 2 minutes process crashed with this error.

```
Error: Error evaluating "
        var pc = conns["6z"]
        var dc = pc.dataChannels[1]
      
        var data = "AABACQcAAAHWAAEAAA=="
        data = base64ToArrayBuffer(data)
        dc.send(data)
        dc.bufferedAmount
      ": Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open' in "[\"4f3\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4f4\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4f5\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4f6\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4f7\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4f8\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4f9\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fa\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fb\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fc\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fd\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fe\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4ff\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fg\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fh\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fi\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fj\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fk\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fl\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fm\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fn\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fo\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fp\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fq\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fr\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fs\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4ft\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fu\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fv\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fw\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fx\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fy\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4fz\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g0\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g1\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g2\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g3\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g4\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g5\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g6\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g7\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g8\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4g9\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4ga\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4gb\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4gc\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4gd\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4ge\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n[\"4gf\",{\"err\":\"Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'\"}]\n"
    at Parser._transform (/home/artur/WebstormProjects/webtorrent-hybrid/node_modules/newline-json/parser.js:30:12)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
```

This error emitted by newline-json parser. But it couldn't evaluate piece of code from RTCDataChannel.js

**Comment by decim** [comment]
By the way I can't reproduce it one more time.

**Comment by mappum** [comment]
Interesting, thank you for filing this issue. I assume this happened because we tried to send on a `RTCDataChannel` which had closed, but the close event had not gotten to the node process.
