### ISSUE TITLE
Periodic EPIPE error

### ISSUE THREAD

**Issue by pfraze** [mappum/electron-webrtc#50]
My application gives an EPIPE error somewhere around 5 minutes into its execution. The error stack is not very useful, but it only occurs when I have electron-webrtc integrated, so I'm fairly sure it's occurring here somewhere.

Here's the stack trace:

```
Uncaught Exception:
Error: write EPIPE
    at exports._errnoException (util.js:949:11)
    at WriteWrap.afterWrite (net.js:793:14)
```

**Comment by pfraze** [comment]
I glanced through the electron-webrtc source and nothing stood out at me, as a possible source. It's possible some code that depends on electron-webrtc (and therefore only executes when it's active in my code) is responsible for this
