### ISSUE TITLE
electron-eval error: Electron process exited with code 0

### ISSUE THREAD

**Issue by kevinejohn** [mappum/electron-webrtc#68]
I have been getting these errors below ever since `electron-webrtc v0.2.9`. It appears the `electron-eval` version was bumped then which probably has something to do with it. Any ideas what's wrong?

Node: v6.4.0
NPM: 3.10.3
OS X 10.11.6 (15G31) and Ubuntu 16.04.1 LTS

## Example program
```
var Peer = require('simple-peer')
var wrtc = require('electron-webrtc')()

wrtc.on('error', function (err, source) {
  console.error(err)
})

var p = new Peer({ initiator: true, trickle: false, wrtc: wrtc })

p.on('signal', function (data) {
  console.log('SIGNAL', JSON.stringify(data))
})
```

### electron-webrtc v0.2.9
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: electron-eval error: Electron process exited with code 0.
Stderr:
[57550:0828/205112:ERROR:webrtcsession.cc(1395)] ConnectDataChannel called when data_channel_ is NULL.
[57550:0828/205122:ERROR:stunport.cc(97)] Binding request timed out from 192.168.1.x:49946 (en0)


    at ChildProcess.<anonymous> (/Users/.../node_modules/electron-eval/lib/index.js:145:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

### electron-webrtc v0.2.10
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: electron-eval error: Electron process exited with code 0.
Stderr:
[57565:0828/205457:ERROR:webrtcsession.cc(1395)] ConnectDataChannel called when data_channel_ is NULL.
[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(295)] CreateAnswer can't be called before SetRemoteDescription.

[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(480)] Create SDP failed: CreateAnswer can't be called before SetRemoteDescription.

[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(295)] CreateAnswer can't be called before SetRemoteDescription.
[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(480)] Create SDP failed: CreateAnswer can't be called before SetRemoteDescription.

[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(295)] CreateAnswer can't be called before SetRemoteDescription.
[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(480)] Create SDP failed: CreateAnswer can't be called before SetRemoteDescription.

[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(295)] CreateAnswer can't be called before SetRemoteDescription.
[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(480)] Create SDP failed: CreateAnswer can't be called before SetRemoteDescription.

[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(295)] CreateAnswer can't be called before SetRemoteDescription.
[57565:0828/205457:ERROR:webrtcsessiondescriptionfactory.cc(480)] Create SDP failed: CreateAnswer can't be called before SetRemoteDescription.

[57565:0828/205507:ERROR:stunport.cc(97)] Binding request timed out from 192.168.1.x:61829 (en0)

[57565:0828/205507:ERROR:webrtcsessiondescriptionfactory.cc(295)] CreateAnswer can't be called before SetRemoteDescription.

[57565:0828/205507:ERROR:webrtcsessiondescriptionfactory.cc(480)] Create SDP failed: CreateAnswer can't be called before SetRemoteDescription.


    at ChildProcess.<anonymous> (/Users/.../node_modules/electron-eval/lib/index.js:145:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by kevinejohn** [comment]
I did a little more digging and it looks like this error starts happening on `electron-eval 0.9.3`

**Comment by mappum** [comment]
The issue causing this in `electron-eval` has been fixed, as well as the issue in `electron-webrtc` causing the errors shown in your output.

**Comment by kevinejohn** [comment]
@mappum thanks!
